development:
  adapter: postgresql
  encoding: unicode
  database: development
  host: localhost
  pool: 5
  username: snow
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: test
  host: localhost
  pool: 5
  username: snow
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: localhost
  pool: 5
  username: snow
  password: password
